name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install package and dev extras
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Lint
        run: |
          ruff check src
      - name: Run tests
        run: |
          pytest
      - name: Verify modules compile
        run: |
          python -m compileall src